### ISSUE TITLE
Adding new NavState for NavEnd

### ISSUE THREAD

**Issue by SRai22** [jlblancoc/selfdriving#9]
Would be very useful if we can have a new internal NavState for NavEngine that indicates NavEnd when on the last waypoint. 
This addition would lead to on_nav_end() callback on VehicleMotionInterface. This would also be used to easily differentiate Nav end on error and normal end.

**Comment by jlblancoc** [comment]
Yeap, it's in my list :-) 
In particular, some on the top: 
- [x] Actually mark waypoints as reached when really reached, and make progress to the next non-skipable one when done.
- [x] Emit events.

**Comment by jlblancoc** [comment]
To be discussed later on (clarify scope / docs / handling on user side):

- virtual void on_path_seems_blocked()  => Replan (no progress in timeout? )

- virtual void on_cannot_get_closer_to_blocked_target() ==> yes, trigger if **target point** is clearly blocked.

- virtual void on_apparent_collision() ==> yes.

- anything to do on pending action timeout? (now: stop and retry)

**Comment by SRai22** [comment]
Was going to suggest the same regarding enqueued_motiom_timeout.
